### ISSUE TITLE
The choice of scheduler

### ISSUE THREAD

**Issue by HarryWang355** [oss-roettger/XL-Textual-Inversion#2]
Thank you for the amazing work. I noticed that you used DDPMScheduler instead of the default EulerDiscreteScheduler in the notebook. I tested with the EulerDiscreteScheduler but it was not working. Do you know why using the default scheduler leads to failure in textual inversion and what is the motivation for choosing DDPM over other alternatives such as DDIM?

**Comment by oss-roettger** [comment]
Dear Yuanhao, 

I have chosen the DDPM scheduler since I assume (= not sure) that SDXL used the standard DDPM noise levels (1000 steps) for the original model training. DDIM works as well because it is just an approximation of DDPM. I don't know enough details on all the other possible schedulers (list below), to tell you why those won't work for TI out of the box.  I guess those schedulers do not predict the genuine noise I 'm using as the target to calculate the loss for the embedding optimization.

Short answer: I'm using the DDPM scheduler because it is working in the TI process. Once the embedding is calculated you may use whatever scheduler you like to generate your images (calculated embeddings are independent of the scheduler). 

 "base.scheduler.compatibles" prints out a list of 14(!) schedulers which should be compatible with SDXL. Maybe you could use some of those for the TI process, but I see no reason why to do so.
